stages:
- test
- package
- deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

run-test:
  stage: test
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
  only:
    - branches
  except:
    - master
    - pre-production
    - production

run-package-dev:
  stage: package
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
    - npm run build:dev
    - pwd
    - ls
  artifacts:
    paths:
      - dist
  only:
    - master

run-deploy-dev:
    stage: deploy
    script:
      - pwd
      - ls
      - mkdir -p /root/.ssh
      - echo "$SSH_PRIVATE_KEY_DEV" |  tr -d '\r' > /root/.ssh/id_rsa
      - echo "$SSH_PRIVATE_KEY_DEV"
     # - echo "$SSH_PUBLIC_KEY_DEV" |  tr -d '\r' > /root/.ssh/id_rsa.pub
     # - echo "$SSH_PUBLIC_KEY_DEV" 
      - chmod 600 /root/.ssh/id_rsa
     # - chmod 644 /root/.ssh/id_rsa.pub
      - chmod 700 /root/.ssh
     # - echo "Host *\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
      - cat /root/.ssh/id_rsa
     #  - cat /root/.ssh/id_rsa.pub
     # - cat /root/.ssh/config
      - ls -la /root/.ssh/
      - scp -P 3031 -r dist/* admin@132.215.33.56:/var/www/html/maponion
    environment:
      name: dev
      url: 132.215.33.56/maponion
    dependencies:
    -  run-package-dev
    only:
     - master



