stages:
- test
- package
- deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

run-test:
  stage: test
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
  only:
    - branches
  except:
    - master
    - pre-production
    - production

run-package-dev:
  stage: package
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
    - npm run build:dev
    - pwd
    - ls
  artifacts:
    paths:
      - dist
  only:
    - master

run-deploy-dev:
    stage: deploy
    script:
      - pwd
      - ls
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY_DEV" | tr -d '\r' | ssh-add - > /dev/null
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - scp -r dist/* admin@132.215.33.56:/var/www/html/maponion
    environment:
      name: dev
      url: 132.215.33.56/maponion
    dependencies:
    -  run-package-dev
    only:
     - master



